# Generated by Django 5.0.1 on 2024-02-06 18:35

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("quoteapp", "0002_alter_author_born_date"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="tag",
            name="tag of username",
        ),
        migrations.RemoveField(
            model_name="tag",
            name="user",
        ),
        migrations.AddConstraint(
            model_name="tag",
            constraint=models.UniqueConstraint(fields=("name",), name="tag"),
        ),
    ]
